import { BUILDINGS, TECHS, UNITS, createInitialState, type TechDef } from "./data";
import type { BuildingType, GameState, ResourceKey, UnitType } from "./types";

export type EngineResult = { ok: boolean; message: string; state: GameState };
const uid = (prefix:string) => `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const nowIso = (now:number) => new Date(now).toISOString();
const moneyKey: ResourceKey = "money";

export function cloneState(state:GameState):GameState { return JSON.parse(JSON.stringify(state)) as GameState; }
export function canAfford(state:GameState,cost:Partial<Record<ResourceKey,number>>):boolean { return Object.entries(cost).every(([k,v]) => (state.resources[k as ResourceKey]?.amount ?? 0) >= (v ?? 0)); }
export function spend(state:GameState,cost:Partial<Record<ResourceKey,number>>) { for(const [k,v] of Object.entries(cost)){ const r=state.resources[k as ResourceKey]; if(r) r.amount-=v || 0; } }
function notify(state:GameState,title:string,body:string,type="system",now=Date.now()){ state.notifications.unshift({id:uid("n"),title,body,type,createdAt:nowIso(now),read:false}); state.notifications=state.notifications.slice(0,80); state.history.unshift({id:uid("h"),text:`${title}: ${body}`,createdAt:nowIso(now)}); state.history=state.history.slice(0,100); }
function result(state:GameState,message:string,ok=true):EngineResult { return {ok,message,state}; }
function fail(state:GameState,message:string):EngineResult { return result(state,message,false); }
function ownedProvince(state:GameState,provinceId:string){ const p=state.provinces.find(x=>x.id===provinceId); return p && p.ownerId===state.player.countryId ? p : undefined; }
function hasBuilding(state:GameState,provinceId:string,type:BuildingType){ return state.buildings.some(b=>b.provinceId===provinceId&&b.type===type); }
function completedTech(state:GameState,id:string){ return state.research.some(t=>t.id===id&&t.status==="completed"); }
function researchFacilityOk(state:GameState,provinceId:string,level=1){ const allowed=level>=5?["nuclearResearchFacility"]:level>=4?["advancedWeaponsLaboratory","nuclearResearchFacility"]:level>=3?["secretLaboratory","advancedWeaponsLaboratory","nuclearResearchFacility"]:level>=2?["advancedResearchCenter","secretLaboratory","advancedWeaponsLaboratory","nuclearResearchFacility"]:["researchCenter","advancedResearchCenter","secretLaboratory","advancedWeaponsLaboratory","nuclearResearchFacility"]; return state.buildings.some(b=>b.provinceId===provinceId&&allowed.includes(b.type)); }

export function reconcile(input:GameState, now=Date.now()):GameState {
  const state=cloneState(input); const last=new Date(state.lastUpdatedAt).getTime(); const elapsed=Math.max(0,(now-last)/1000); if(elapsed<0) return state;
  for(const key of Object.keys(state.resources) as ResourceKey[]){ const r=state.resources[key]; const delta=(r.productionPerHour-r.consumptionPerHour)*elapsed/3600; r.amount=Math.max(0,Math.min(r.capacity,r.amount+delta)); }
  state.lastUpdatedAt=nowIso(now); state.worldTime=nowIso(now);
  const completedBuildings=state.construction.filter(o=>new Date(o.endsAt).getTime()<=now);
  for(const o of completedBuildings){ const existing=state.buildings.find(b=>b.provinceId===o.provinceId&&b.type===o.type); if(existing) existing.level+=1; else state.buildings.push({id:uid("b"),type:o.type,provinceId:o.provinceId,level:1,builtAt:o.endsAt}); const p=state.provinces.find(x=>x.id===o.provinceId); if(p&&!existing) p.buildingIds.push(state.buildings[state.buildings.length-1].id); const def=BUILDINGS[o.type]; notify(state,"Construction Complete",`${def.name} is operational in ${p?.name ?? "province"}.`,"construction",now); }
  state.construction=state.construction.filter(o=>new Date(o.endsAt).getTime()>now);
  const completedResearch=state.research.filter(t=>t.status==="researching"&&t.endsAt&&new Date(t.endsAt).getTime()<=now);
  for(const t of completedResearch){ t.status="completed"; delete t.endsAt; notify(state,"Research Complete",`${t.name} is now available to the dominion.`,"research",now); }
  for(const t of state.research){ if(t.status==="locked"&&t.prerequisites.every(id=>completedTech(state,id))) t.status="available"; }
  const doneProduction=state.production.filter(o=>new Date(o.endsAt).getTime()<=now);
  for(const o of doneProduction){ const def=UNITS[o.unitType]; for(let i=0;i<o.quantity;i++){ state.units.push({id:uid("u"),type:o.unitType,name:`${def.name} ${Math.floor(Math.random()*900+100)}`,countryId:state.player.countryId,provinceId:o.provinceId,health:100,morale:80,strength:100,fuel:100,ammunition:100}); } notify(state,"Unit Ready",`${o.quantity} × ${def.name} ready in ${state.provinces.find(p=>p.id===o.provinceId)?.name ?? "province"}.`,"military",now); }
  state.production=state.production.filter(o=>new Date(o.endsAt).getTime()>now);
  for(const army of state.armies){ if(army.status==="moving"&&army.arrivesAt&&new Date(army.arrivesAt).getTime()<=now&&army.destinationProvinceId){ const from=state.provinces.find(p=>p.id===army.provinceId); const to=state.provinces.find(p=>p.id===army.destinationProvinceId); if(from) from.armyIds=from.armyIds.filter(id=>id!==army.id); if(to&&!to.armyIds.includes(army.id)) to.armyIds.push(army.id); army.provinceId=army.destinationProvinceId; army.status="ready"; delete army.destinationProvinceId; delete army.arrivesAt; delete army.startedAt; notify(state,"Army Arrived",`${army.name} reached ${to?.name ?? "destination"}.`,"military",now); }
  }
  for(const battle of state.battles.filter(b=>b.status==="ongoing"&&new Date(b.resolvesAt).getTime()<=now)) resolveBattleInPlace(state,battle.id,now);
  for(const item of state.market){ const pressure=(item.demand-item.supply)/1000; item.price=Math.max(0.5,Number((item.price*(1+pressure)).toFixed(2))); item.supply=Math.max(10,Math.min(200,item.supply+(Math.random()*4-2))); item.demand=Math.max(10,Math.min(200,item.demand+(Math.random()*4-2))); }
  return state;
}

export function startConstruction(input:GameState,provinceId:string,type:BuildingType,now=Date.now()):EngineResult { const state=cloneState(input); const p=ownedProvince(state,provinceId); if(!p) return fail(state,"You can only build in territory you control."); const def=BUILDINGS[type]; if(!def) return fail(state,"Unknown building."); if(p.buildingIds.length>=p.slots) return fail(state,"No free building slots in this province."); if(hasBuilding(state,provinceId,type)) return fail(state,`${def.name} already exists here. Use Upgrade instead.`); if(def.req?.some(r=>!hasBuilding(state,provinceId,r))) return fail(state,`Requires: ${def.req.map(r=>BUILDINGS[r].name).join(", ")}.`); if(!canAfford(state,def.cost)) return fail(state,"Insufficient resources."); spend(state,def.cost); const end=now+def.time*1000; state.construction.push({id:uid("build"),provinceId,type,startedAt:nowIso(now),endsAt:nowIso(end)}); notify(state,"Construction Started",`${def.name} started in ${p.name}.`,"construction",now); return result(state,`${def.name} will complete in ${def.time}s.`); }
export function collectOutput(input:GameState,buildingId:string,now=Date.now()):EngineResult {
  const state=cloneState(input); const b=state.buildings.find(x=>x.id===buildingId); if(!b) return fail(state,"Building not found."); const p=ownedProvince(state,b.provinceId); if(!p) return fail(state,"You do not control this province."); const def=BUILDINGS[b.type]; const output=def.production??{}; let total=0; for(const [k,v] of Object.entries(output)){ const r=state.resources[k as ResourceKey]; if(r){ const amount=Math.round((v??0)*Math.max(1,b.level)/4); r.amount=Math.min(r.capacity,r.amount+amount); total+=amount; } } if(total===0) return fail(state,"This facility has no collectible output."); notify(state,"Production Collected",`${def.name} output collected in ${p.name}.`,"economy",now); return result(state,`${def.name} output collected.`); }

export function upgradeBuilding(input:GameState,buildingId:string,now=Date.now()):EngineResult { const state=cloneState(input); const b=state.buildings.find(x=>x.id===buildingId); if(!b) return fail(state,"Building not found."); const p=ownedProvince(state,b.provinceId); if(!p) return fail(state,"You do not control this province."); const def=BUILDINGS[b.type]; const cost:Partial<Record<ResourceKey,number>>={}; for(const [k,v] of Object.entries(def.cost)) cost[k as ResourceKey]=Math.round((v??0)*(1+b.level*0.65)); if(!canAfford(state,cost)) return fail(state,"Insufficient resources for upgrade."); spend(state,cost); const end=now+Math.round(def.time*(1+b.level*.55))*1000; state.construction.push({id:uid("upgrade"),provinceId:b.provinceId,type:b.type,startedAt:nowIso(now),endsAt:nowIso(end)}); notify(state,"Upgrade Queued",`${def.name} level ${b.level+1} queued in ${p.name}.`,"construction",now); return result(state,`Upgrade queued for ${def.name}.`); }
export function startResearch(input:GameState,techId:string,provinceId:string,now=Date.now()):EngineResult { const state=cloneState(input); const tech=state.research.find(t=>t.id===techId); if(!tech) return fail(state,"Technology not found."); if(tech.status!=="available") return fail(state,tech.status==="completed"?"Technology already completed.":"Technology is not currently available."); if(!ownedProvince(state,provinceId)) return fail(state,"Research must be conducted in your territory."); if(!researchFacilityOk(state,provinceId,tech.level)) return fail(state,tech.level>=5?"Requires a Nuclear Research Facility.":tech.level>=4?"Requires an Advanced Weapons Laboratory.":tech.level>=3?"Requires a Secret Laboratory.":tech.level>=2?"Requires an Advanced Research Center.":"Build a Research Center first."); const def=TECHS.find(t=>t.id===techId) as TechDef; if(!canAfford(state,def.cost)) return fail(state,"Insufficient resources."); spend(state,def.cost); tech.status="researching"; tech.endsAt=nowIso(now+def.durationSec*1000); notify(state,"Research Started",`${tech.name} is researching.`,"research",now); return result(state,`${tech.name} will complete in ${def.durationSec}s.`); }
export function startProduction(input:GameState,provinceId:string,unitType:UnitType,quantity:number,now=Date.now()):EngineResult { const state=cloneState(input); const p=ownedProvince(state,provinceId); if(!p) return fail(state,"You do not control this province."); const def=UNITS[unitType]; if(!def) return fail(state,"Unknown unit."); if(!hasBuilding(state,provinceId,def.building)) return fail(state,`Requires ${BUILDINGS[def.building].name}.`); if(def.domain==="air"&&!hasBuilding(state,provinceId,"airfield")) return fail(state,"Aircraft require an Airfield."); if(def.domain==="naval"&&!hasBuilding(state,provinceId,"port")&&!hasBuilding(state,provinceId,"navalBase")) return fail(state,"Naval units require a Port or Naval Base."); if(!completedTech(state,def.tech)) return fail(state,`Requires research: ${state.research.find(t=>t.id===def.tech)?.name ?? def.tech}.`); const qty=Math.max(1,Math.min(20,Math.floor(quantity))); const cost:Partial<Record<ResourceKey,number>>={}; for(const [k,v] of Object.entries(def.cost)) cost[k as ResourceKey]=(v??0)*qty; if(!canAfford(state,cost)) return fail(state,"Insufficient resources."); spend(state,cost); const end=now+def.time*qty*1000; state.production.push({id:uid("prod"),provinceId,unitType,quantity:qty,startedAt:nowIso(now),endsAt:nowIso(end)}); notify(state,"Production Started",`${qty} × ${def.name} queued in ${p.name}.`,"production",now); return result(state,`${qty} × ${def.name} entered the queue.`); }
export function createArmy(input:GameState,provinceId:string,name:string,now=Date.now()):EngineResult { const state=cloneState(input); const p=ownedProvince(state,provinceId); if(!p) return fail(state,"Create armies in your territory."); const army={id:uid("army"),name:name.trim()||"New Army",countryId:state.player.countryId,provinceId,unitIds:[],commander:state.player.rank,status:"ready" as const}; state.armies.push(army); p.armyIds.push(army.id); notify(state,"Army Formed",`${army.name} established in ${p.name}.`,"military",now); return result(state,`${army.name} created.`); }
export function assignUnits(input:GameState,armyId:string,unitIds:string[]):EngineResult { const state=cloneState(input); const army=state.armies.find(a=>a.id===armyId); if(!army) return fail(state,"Army not found."); const valid=unitIds.filter(id=>{const u=state.units.find(x=>x.id===id); return u&&u.countryId===state.player.countryId&&u.provinceId===army.provinceId;}); for(const id of valid){ for(const other of state.armies){ if(other.id!==army.id) other.unitIds=other.unitIds.filter(x=>x!==id); } } army.unitIds=Array.from(new Set([...army.unitIds,...valid])); return result(state,`${valid.length} unit(s) assigned.`); }
function travelSeconds(a:GameState,from:string,to:string,armyId:string){ const A=a.provinces.find(p=>p.id===from),B=a.provinces.find(p=>p.id===to); const terrainPenalty=B?.terrain==="mountain"?1.7:B?.terrain==="forest"?1.3:1; const strength=a.armies.find(x=>x.id===armyId)?.unitIds.length??1; return Math.round((20+Math.abs((A?.population??0)-(B?.population??0))/10000000+strength*3)*terrainPenalty); }
export function moveArmy(input:GameState,armyId:string,destinationProvinceId:string,now=Date.now()):EngineResult { const state=cloneState(input); const army=state.armies.find(a=>a.id===armyId); const dest=state.provinces.find(p=>p.id===destinationProvinceId); if(!army||!dest) return fail(state,"Army or destination not found."); if(army.countryId!==state.player.countryId) return fail(state,"You do not command this army."); if(army.status!=="ready") return fail(state,"Army is already committed to an order."); const sec=travelSeconds(state,army.provinceId,destinationProvinceId,armyId); army.status="moving"; army.destinationProvinceId=destinationProvinceId; army.startedAt=nowIso(now); army.arrivesAt=nowIso(now+sec*1000); notify(state,"Movement Ordered",`${army.name} moving to ${dest.name}. ETA ${sec}s.`,"military",now); return result(state,`Movement order accepted. ETA ${sec}s.`); }
export function attackProvince(input:GameState,armyId:string,targetProvinceId:string,now=Date.now()):EngineResult { const state=cloneState(input); const army=state.armies.find(a=>a.id===armyId); const target=state.provinces.find(p=>p.id===targetProvinceId); if(!army||!target) return fail(state,"Army or target not found."); if(target.ownerId===state.player.countryId) return fail(state,"That province is already under your control."); if(army.status!=="ready") return fail(state,"Army is not ready."); const defenderUnits=state.units.filter(u=>u.provinceId===targetProvinceId&&u.countryId===target.ownerId); const attackerStrength=army.unitIds.reduce((sum,id)=>{const u=state.units.find(x=>x.id===id); return sum+(u?UNITS[u.type].attack*u.strength/100:0)},0); const defenderStrength=defenderUnits.reduce((sum,u)=>sum+UNITS[u.type].defense*u.strength/100,0)+state.buildings.filter(b=>b.provinceId===targetProvinceId&&["fortification","bunker","coastalDefense"].includes(b.type)).reduce((s,b)=>s+b.level*40,0); const battleId=uid("battle"); state.battles.push({id:battleId,name:`${state.provinces.find(p=>p.id===army.provinceId)?.name} Offensive`,provinceId:targetProvinceId,attackerArmyId:army.id,defenderCountryId:target.ownerId,startedAt:nowIso(now),resolvesAt:nowIso(now+12000),attackerStrength:Math.max(1,attackerStrength),defenderStrength:Math.max(1,defenderStrength),status:"ongoing",casualtiesAttacker:0,casualtiesDefender:0}); army.status="attacking"; army.targetProvinceId=targetProvinceId; let war=state.wars.find(w=>(w.attackerId===state.player.countryId&&w.defenderId===target.ownerId)||(w.attackerId===target.ownerId&&w.defenderId===state.player.countryId)); if(!war){ war={id:uid("war"),name:`Dominion War — ${target.name}`,attackerId:state.player.countryId,defenderId:target.ownerId,startedAt:nowIso(now),score:0,status:"active",battleIds:[]}; state.wars.unshift(war); const rel=state.diplomacy.find(r=>(r.a===state.player.countryId&&r.b===target.ownerId)||(r.b===state.player.countryId&&r.a===target.ownerId)); if(rel) rel.status="war"; } war.battleIds.push(battleId); notify(state,"Battle Started",`${army.name} is engaging forces in ${target.name}.`,"war",now); return result(state,`Battle underway in ${target.name}.`); }
function resolveBattleInPlace(state:GameState,battleId:string,now=Date.now()){ const battle=state.battles.find(b=>b.id===battleId); if(!battle||battle.status!=="ongoing") return; const army=state.armies.find(a=>a.id===battle.attackerArmyId); if(!army) return; const win=battle.attackerStrength>=battle.defenderStrength*(0.78+Math.random()*.35); battle.status=win?"attacker_won":"defender_won"; battle.casualtiesAttacker=Math.round(Math.min(battle.attackerStrength,battle.attackerStrength*(win?.18:.35))); battle.casualtiesDefender=Math.round(Math.min(battle.defenderStrength,battle.defenderStrength*(win?.45:.22))); const target=state.provinces.find(p=>p.id===battle.provinceId); const attackerCountry=state.player.countryId; if(win&&target){ const old=target.ownerId; target.ownerId=attackerCountry; target.morale=45; target.armyIds=target.armyIds.filter(id=>id!==army.id); if(!target.armyIds.includes(army.id)) target.armyIds.push(army.id); army.provinceId=target.id; army.status="ready"; delete army.targetProvinceId; state.player.victoryPoints+=target.victoryPoints; state.player.power+=Math.round(target.victoryPoints*15000); state.player.kills+=battle.casualtiesDefender; const city=state.cities.find(c=>c.provinceId===target.id); if(city) city.ownerId=attackerCountry; const war=state.wars.find(w=>w.battleIds.includes(battle.id)); if(war) war.score+=target.victoryPoints*5; notify(state,"Province Captured",`${target.name} is now under your control. +${target.victoryPoints} Victory Points.`,"war",now); } else { army.status="ready"; delete army.targetProvinceId; state.player.kills+=Math.round(battle.casualtiesDefender*.4); notify(state,"Battle Lost",`Your forces failed to capture ${target?.name ?? "the province"}.`,"war",now); } }
export function resolveBattle(input:GameState,battleId:string,now=Date.now()):EngineResult { const state=cloneState(input); resolveBattleInPlace(state,battleId,now); return result(state,"Battle resolved."); }
export function marketTrade(input:GameState,resource:ResourceKey,quantity:number,side:"buy"|"sell",now=Date.now()):EngineResult { const state=cloneState(input); const item=state.market.find(m=>m.resource===resource); if(!item) return fail(state,"Market item not found."); const qty=Math.max(1,Math.min(10000,Math.floor(quantity))); const total=Number((qty*item.price).toFixed(2)); if(side==="buy"){ if(item.stock<qty) return fail(state,"Market stock is insufficient."); if(state.resources.money.amount<total) return fail(state,"Insufficient money."); state.resources.money.amount-=total; state.resources[resource].amount=Math.min(state.resources[resource].capacity,state.resources[resource].amount+qty); item.stock-=qty; item.supply=Math.max(1,item.supply-qty/100); item.demand=Math.min(200,item.demand+qty/100); } else { if(resource==="money") return fail(state,"Money cannot be sold on this market."); if(state.resources[resource].amount<qty) return fail(state,"Insufficient resource stock."); state.resources[resource].amount-=qty; state.resources.money.amount+=total; item.stock+=qty; item.supply=Math.min(200,item.supply+qty/100); item.demand=Math.max(1,item.demand-qty/100); } notify(state,"Market Transaction",`${side.toUpperCase()} ${qty} ${resource} for ${total.toFixed(2)} GD$.`,"market",now); return result(state,`${side.toUpperCase()} complete.`); }
export function setDiplomacy(input:GameState,targetCountryId:string,status:"peace"|"trade"|"right_of_way"|"embargo",now=Date.now()):EngineResult { const state=cloneState(input); const rel=state.diplomacy.find(r=>(r.a===state.player.countryId&&r.b===targetCountryId)||(r.b===state.player.countryId&&r.a===targetCountryId)); if(!rel) return fail(state,"Diplomatic relation not found."); rel.status=status; notify(state,"Diplomatic Status Updated",`${state.countries.find(c=>c.id===targetCountryId)?.name ?? targetCountryId}: ${status.replace(/_/g," ")}.`,"diplomacy",now); return result(state,"Diplomatic status updated."); }
export function inviteAllianceMember(input:GameState,playerId:string,now=Date.now()):EngineResult { const state=cloneState(input); if(state.alliance.memberIds.includes(playerId)) return fail(state,"Player is already in the alliance."); state.alliance.memberIds.push(playerId); state.alliance.power+=2500000; state.alliance.missions.find(m=>m.id==="capture")!.progress=Math.min(state.alliance.missions.find(m=>m.id==="capture")!.target,state.alliance.missions.find(m=>m.id==="capture")!.progress+0); notify(state,"Alliance Invitation",`Invitation created for ${playerId}.`,"alliance",now); return result(state,"Alliance invitation created."); }
export function recruitAgent(input:GameState,provinceId:string,mission:"recon"|"sabotage"|"counter"="recon",now=Date.now()):EngineResult { const state=cloneState(input); const p=ownedProvince(state,provinceId); if(!p) return fail(state,"Agent must operate from controlled territory."); const cost={money:250}; if(!canAfford(state,cost)) return fail(state,"Insufficient money."); spend(state,cost); const agent={id:uid("agent"),name:`Agent ${Math.floor(Math.random()*900+100)}`,provinceId,mission,successChance:mission==="counter"?.8:.65,endsAt:nowIso(now+60000)}; state.intelligence.push(agent); notify(state,"Agent Deployed",`${agent.name} assigned to ${mission}.`,"intelligence",now); return result(state,`${agent.name} deployed.`); }
export function sendChat(input:GameState,text:string,channel:"global"|"alliance"|"private"="global",now=Date.now()):EngineResult { const state=cloneState(input); const body=text.trim(); if(!body) return fail(state,"Message cannot be empty."); state.chat.push({channel,sender:state.player.username,text:body,createdAt:nowIso(now)}); state.chat=state.chat.slice(-100); return result(state,"Message sent."); }

export function declareWar(input:GameState,targetCountryId:string,now=Date.now()):EngineResult { const state=cloneState(input); if(targetCountryId===state.player.countryId) return fail(state,"You cannot declare war on yourself."); if(state.wars.some(w=>w.status==="active"&&((w.attackerId===state.player.countryId&&w.defenderId===targetCountryId)||(w.defenderId===state.player.countryId&&w.attackerId===targetCountryId)))) return fail(state,"You are already at war with this power."); state.wars.unshift({id:uid("war"),name:`Dominion War`,attackerId:state.player.countryId,defenderId:targetCountryId,startedAt:nowIso(now),score:0,status:"active",battleIds:[]}); const rel=state.diplomacy.find(r=>(r.a===state.player.countryId&&r.b===targetCountryId)||(r.b===state.player.countryId&&r.a===targetCountryId)); if(rel) rel.status="war"; notify(state,"War Declared",`War has been declared against ${state.countries.find(c=>c.id===targetCountryId)?.name ?? targetCountryId}.`,"war",now); return result(state,"War declared."); }
export function changeRank(input:GameState,rank:string):EngineResult { const state=cloneState(input); const ranks=["General der Infanterie","Generaloberst","Feldreichsmarschall","Obergruppenführer","Reichsführer","Führer"]; const idx=ranks.indexOf(rank); if(idx<0) return fail(state,"Unknown rank."); const required=idx*25; if(state.player.victoryPoints<required) return fail(state,`Requires ${required} Victory Points.`); state.player.rank=rank; for(const a of state.armies) if(a.countryId===state.player.countryId) a.commander=rank; notify(state,"Rank Updated",`You are now ${rank}.`,"profile"); return result(state,`Rank changed to ${rank}.`); }
export function markNotificationRead(input:GameState,id:string):GameState { const state=cloneState(input); const n=state.notifications.find(x=>x.id===id); if(n) n.read=true; return state; }
export function createGameState(now=Date.now()){ return createInitialState(now); }
