export type ResourceKey = "food" | "steel" | "oil" | "aluminum" | "copper" | "rareMaterials" | "manpower" | "money" | "premium";
export type Terrain = "urban" | "plains" | "forest" | "mountain" | "desert" | "coastal";
export type UnitType = "infantry" | "motorized" | "mechanized" | "special" | "recon" | "lightTank" | "mediumTank" | "heavyTank" | "mbt" | "tankDestroyer" | "spg" | "fieldArtillery" | "heavyArtillery" | "rocketArtillery" | "antiTank" | "antiAir" | "fighter" | "interceptor" | "cas" | "tacticalBomber" | "strategicBomber" | "transportAircraft" | "reconAircraft" | "navalBomber" | "destroyer" | "submarine" | "cruiser" | "battleship" | "carrier" | "transportShip" | "landingShip" | "missileCruiser" | "rocket" | "tacticalMissile" | "cruiseMissile" | "ballisticMissile" | "strategicMissile" | "nuclearMissile";
export type BuildingType = "farm" | "steelMill" | "oilRefinery" | "aluminumWorks" | "copperMine" | "rareMaterialsFacility" | "industry" | "advancedIndustry" | "warehouse" | "infrastructure" | "barracks" | "motorPool" | "tankPlant" | "ordnanceFactory" | "artilleryFactory" | "mechanizedFactory" | "aircraftFactory" | "airfield" | "advancedAirfield" | "radarStation" | "navalBase" | "shipyard" | "advancedShipyard" | "port" | "navalLogistics" | "missileFactory" | "rocketFacility" | "missileResearchFacility" | "strategicWeaponsFacility" | "researchCenter" | "advancedResearchCenter" | "secretLaboratory" | "advancedWeaponsLaboratory" | "nuclearResearchFacility" | "fortification" | "bunker" | "coastalDefense" | "antiAirDefense" | "radar" | "capital" | "commandCenter" | "communicationsCenter" | "intelligenceCenter" | "logisticsCenter" | "hospital";
export type TechCategory = "infantry" | "armor" | "artillery" | "air" | "naval" | "missiles" | "strategic" | "nuclear" | "economy" | "industry" | "secret";

export interface ResourceStock { amount: number; capacity: number; productionPerHour: number; consumptionPerHour: number; }
export interface PlayerState { id: string; username: string; countryId: string; rank: string; level: number; xp: number; power: number; kills: number; victoryPoints: number; money: number; premium: number; }
export interface ProvinceState { id: string; name: string; ownerId: string; countryId: string; terrain: Terrain; population: number; morale: number; resource: ResourceKey; production: number; slots: number; cityId?: string; coastal?: boolean; port?: boolean; airfield?: boolean; victoryPoints: number; buildingIds: string[]; armyIds: string[]; }
export interface CityState { id: string; name: string; provinceId: string; ownerId: string; capital?: boolean; population: number; morale: number; }
export interface BuildingInstance { id: string; type: BuildingType; provinceId: string; level: number; builtAt: string; }
export interface ResearchState { id: string; name: string; category: TechCategory; level: number; cost: Partial<Record<ResourceKey, number>>; durationSec: number; prerequisites: string[]; status: "locked" | "available" | "researching" | "completed"; endsAt?: string; }
export interface ProductionOrder { id: string; provinceId: string; unitType: UnitType; quantity: number; startedAt: string; endsAt: string; }
export interface ConstructionOrder { id: string; provinceId: string; type: BuildingType; startedAt: string; endsAt: string; }
export interface UnitState { id: string; type: UnitType; name: string; countryId: string; provinceId: string; health: number; morale: number; strength: number; fuel: number; ammunition: number; }
export interface ArmyState { id: string; name: string; countryId: string; provinceId: string; unitIds: string[]; commander: string; status: "ready" | "moving" | "attacking" | "defending"; destinationProvinceId?: string; startedAt?: string; arrivesAt?: string; targetProvinceId?: string; }
export interface BattleState { id: string; name: string; provinceId: string; attackerArmyId: string; defenderCountryId: string; startedAt: string; resolvesAt: string; attackerStrength: number; defenderStrength: number; status: "ongoing" | "attacker_won" | "defender_won"; casualtiesAttacker: number; casualtiesDefender: number; }
export interface WarState { id: string; name: string; attackerId: string; defenderId: string; startedAt: string; score: number; status: "active" | "ended"; battleIds: string[]; }
export interface MarketItem { resource: ResourceKey; stock: number; price: number; supply: number; demand: number; }
export interface Notification { id: string; title: string; body: string; type: string; createdAt: string; read: boolean; }
export interface AllianceState { id: string; name: string; leaderId: string; memberIds: string[]; power: number; missions: { id: string; title: string; progress: number; target: number }[]; }
export interface IntelligenceAgent { id: string; name: string; provinceId: string; mission: "recon" | "sabotage" | "counter"; successChance: number; endsAt: string; }
export interface DiplomacyRelation { a: string; b: string; status: "peace" | "war" | "trade" | "right_of_way" | "embargo"; }
export interface HistoryEntry { id: string; text: string; createdAt: string; }
export interface GameState {
  version: 2; worldTime: string; lastUpdatedAt: string; chat: { channel: "global"|"alliance"|"private"; sender: string; text: string; createdAt: string }[]; player: PlayerState; countries: { id: string; name: string; code: string; capital: string; color: string; bloc: string; power: number }[];
  resources: Record<ResourceKey, ResourceStock>; provinces: ProvinceState[]; cities: CityState[]; buildings: BuildingInstance[]; construction: ConstructionOrder[]; research: ResearchState[]; production: ProductionOrder[]; units: UnitState[]; armies: ArmyState[]; battles: BattleState[]; wars: WarState[]; market: MarketItem[]; notifications: Notification[]; alliance: AllianceState; intelligence: IntelligenceAgent[]; diplomacy: DiplomacyRelation[]; history: HistoryEntry[]; selectedProvinceId?: string; selectedCityId?: string; selectedArmyId?: string;
}
