import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text } from "react-native";
import { Screen, Card, Title, Muted } from "../../components/ui";
import { COLORS } from "../../constants/colors";
import { apiClient } from "../../services/api";
export default function WarScreen(){const [wars,setWars]=useState<any[]>([]);const [battles,setBattles]=useState<any[]>([]);
 const load=async()=>{try{setWars(await apiClient.get<any[]>("/wars/active"));setBattles(await apiClient.get<any[]>("/wars/battles"))}catch{}};useEffect(()=>{load();const i=setInterval(load,5000);return()=>clearInterval(i)},[]);
 const join=async(w:any,side:string)=>{try{await apiClient.post(`/wars/${w.id}/join`,{side});Alert.alert("Joined war","You can now participate.");}catch(e:any){Alert.alert("Cannot join",e?.message||"Travel to a city controlled by that side first.")}};
 return <Screen><ScrollView><Title>Wars</Title><Muted>Live conflicts, fronts and battles.</Muted>{wars.map(w=><Card key={w.id}><Text style={s.title}>{w.attackerCountryId} ⚔ {w.defenderCountryId}</Text><Text style={s.text}>{w.reason||"Active conflict"} · {w.status}</Text><Pressable onPress={()=>join(w,"attacker")}><Text style={s.button}>JOIN ATTACKER</Text></Pressable><Pressable onPress={()=>join(w,"defender")}><Text style={s.button}>JOIN DEFENDER</Text></Pressable></Card>)}<Title>Active battles</Title>{battles.map(b=><Card key={b.id}><Text style={s.title}>{b.location}</Text><Text style={s.text}>Attacker {Math.round(b.attackerStrength)} · Defender {Math.round(b.defenderStrength)} · {Math.round(b.progress)}% · {b.status}</Text>{b.status==="active" && <Pressable onPress={async()=>{try{await apiClient.post(`/wars/battles/${encodeURIComponent(b.id)}/resolve`,{});await load();Alert.alert("Battle resolved","The server applied the result and updated territory control.")}catch(e:any){Alert.alert("Resolution failed",e?.message||"Server rejected the battle resolution.")}}}><Text style={s.button}>RESOLVE BATTLE</Text></Pressable>}</Card>)}</ScrollView></Screen>}
const s=StyleSheet.create({title:{color:COLORS.textPrimary,fontSize:17,fontWeight:"900"},text:{color:COLORS.textMuted,marginVertical:6},button:{color:COLORS.accentGold,fontWeight:"900",paddingVertical:8}});