
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { useGame } from "../../context/GameContext";
import { Button, Card, ProgressBar, Screen, SectionHeader } from "../../components/ui";
const remaining=(iso:string)=>Math.max(0,Math.ceil((new Date(iso).getTime()-Date.now())/1000));
const fmt=(n:number)=>Math.round(n).toLocaleString();
export default function WorkScreen(){const router=useRouter();const {state,collectOutput,upgradeBuilding,refreshTimers}=useGame();const owned=state.provinces.filter(p=>p.ownerId===state.player.countryId);const active=state.construction;const production=state.production;const buildingRows=owned.flatMap(p=>state.buildings.filter(b=>b.provinceId===p.id).map(b=>({p,b})));return <Screen style={styles.screen}><ScrollView contentContainerStyle={{paddingBottom:30}}><SectionHeader title="WORK" action={<Text style={styles.money}>✦ {fmt(state.resources.money.amount)}</Text>}/><Text style={styles.subtitle}>Industry, construction and production queues.</Text><Card><SectionHeader title="ACTIVE QUEUES"/>{active.length===0&&production.length===0?<Text style={styles.muted}>No active orders. Your factories are standing by.</Text>:null}{active.map(o=>{const p=state.provinces.find(x=>x.id===o.provinceId);const pct=1-remaining(o.endsAt)/Math.max(1,(new Date(o.endsAt).getTime()-new Date(o.startedAt).getTime())/1000);return <View key={o.id} style={styles.queue}><View style={styles.row}><Text style={styles.name}>{o.type.replace(/([A-Z])/g," $1")}</Text><Text style={styles.timer}>{remaining(o.endsAt)}s</Text></View><Text style={styles.muted}>{p?.name}</Text><ProgressBar value={pct*100}/></View>})}{production.map(o=><View key={o.id} style={styles.queue}><View style={styles.row}><Text style={styles.name}>{o.quantity} × {o.unitType.replace(/([A-Z])/g," $1")}</Text><Text style={styles.timer}>{remaining(o.endsAt)}s</Text></View><Text style={styles.muted}>{state.provinces.find(p=>p.id===o.provinceId)?.name}</Text><ProgressBar value={(1-remaining(o.endsAt)/Math.max(1,(new Date(o.endsAt).getTime()-new Date(o.startedAt).getTime())/1000))*100}/></View>)}</Card><Card><SectionHeader title="FACILITIES"/>{buildingRows.map(({p,b})=>{const def=b.type.replace(/([A-Z])/g," $1");return <View key={b.id} style={styles.facility}><View style={{flex:1}}><Text style={styles.name}>{def.toUpperCase()}</Text><Text style={styles.muted}>{p.name} · LEVEL {b.level}</Text></View><Button title="UPGRADE" variant="gold" onPress={()=>{const r=upgradeBuilding(b.id);if(r.ok)refreshTimers()}}/></View>})}</Card><Card><SectionHeader title="COLLECTIBLE OUTPUT"/><View style={styles.resourceGrid}>{(["food","steel","oil","aluminum","copper","rareMaterials"] as const).map(k=><View key={k} style={styles.resourceBox}><Text style={styles.resName}>{k.replace(/([A-Z])/g," $1")}</Text><Text style={styles.resValue}>{fmt(state.resources[k].amount)}</Text><Text style={styles.rate}>+{fmt(state.resources[k].productionPerHour)}/h</Text></View>)}</View></Card><Button title="OPEN BUILD QUEUE" variant="gold" onPress={()=>router.push("/build")}/></ScrollView></Screen>}
const styles=StyleSheet.create({screen:{paddingTop:10},subtitle:{color:"#777F84",fontSize:11,marginBottom:10},money:{color:"#D7B36B",fontWeight:"900",fontSize:12},queue:{paddingVertical:8,borderBottomWidth:1,borderBottomColor:"#252D32"},row:{flexDirection:"row",justifyContent:"space-between"},name:{color:"#E9E0CE",fontWeight:"900",fontSize:11},muted:{color:"#78838A",fontSize:9,marginTop:3},timer:{color:"#D7B36B",fontSize:10,fontWeight:"900"},facility:{flexDirection:"row",alignItems:"center",paddingVertical:8,borderBottomWidth:1,borderBottomColor:"#252D32",gap:8},resourceGrid:{flexDirection:"row",flexWrap:"wrap",gap:6},resourceBox:{width:"31%",backgroundColor:"#10181E",borderWidth:1,borderColor:"#29343A",padding:8},resName:{color:"#7F898E",fontSize:8,textTransform:"uppercase"},resValue:{color:"#E2D5B3",fontSize:12,fontWeight:"900",marginTop:3},rate:{color:"#5FAE7A",fontSize:8,marginTop:2}});
