import React, { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from "react";
import { AppState } from "react-native";
import { getItem, setItem } from "../utils/storage";
import { createGameState, reconcile, startConstruction, collectOutput, upgradeBuilding, startResearch, startProduction, createArmy, assignUnits, moveArmy, attackProvince, resolveBattle, marketTrade, declareWar, changeRank, setDiplomacy, inviteAllianceMember, recruitAgent, sendChat, markNotificationRead, type EngineResult } from "../game/engine";
import type { BuildingType, GameState, ResourceKey, UnitType } from "../game/types";
import { DEMO_COUNTRIES, type DemoCountry, type DemoResource, type DemoUnit, type DemoWar, type DemoRevolution } from "../data/mock";

const GAME_KEY = "@gd/game_state_v2";
interface GameContextValue {
  state: GameState; countries: DemoCountry[]; resources: DemoResource[]; units: DemoUnit[]; wars: DemoWar[]; events: GameState["notifications"];
  selectedCountryId: string | null; selectedProvinceId?: string; selectedCityId?: string; selectedArmyId?: string;
  setSelectedCountryId:(id:string|null)=>void; selectProvince:(id:string)=>void; selectCity:(id:string)=>void; selectArmy:(id:string)=>void;
  tickCount:number; advanceTick:()=>void; save:()=>Promise<void>; refreshTimers:()=>void;
  startConstruction:(provinceId:string,type:BuildingType)=>EngineResult; collectOutput:(buildingId:string)=>EngineResult; upgradeBuilding:(buildingId:string)=>EngineResult; startResearch:(techId:string,provinceId?:string)=>EngineResult; startProduction:(provinceId:string,type:UnitType,qty?:number)=>EngineResult; createArmy:(provinceId:string,name:string)=>EngineResult; assignUnits:(armyId:string,unitIds:string[])=>EngineResult; moveArmy:(armyId:string,destination:string)=>EngineResult; attackProvince:(armyId:string,target:string)=>EngineResult; resolveBattle:(battleId:string)=>EngineResult; marketTrade:(resource:ResourceKey,quantity:number,side:"buy"|"sell")=>EngineResult; setDiplomacy:(target:string,status:"peace"|"trade"|"right_of_way"|"embargo")=>EngineResult; inviteAllianceMember:(playerId:string)=>EngineResult; recruitAgent:(provinceId:string,mission?:"recon"|"sabotage"|"counter")=>EngineResult; sendChat:(text:string,channel?:"global"|"alliance"|"private")=>EngineResult; declareWar:(targetCountryId:string)=>EngineResult; changeRank:(rank:string)=>EngineResult; markNotificationRead:(id:string)=>void;
  // Compatibility surface for existing screens.
  revolutions: DemoRevolution[]; startRevolution:(countryId:string,goal:"independence"|"regime_change"|"secession",leaderName:string)=>{success:boolean;message:string}; supportIndependence:(countryId:string,amount?:number)=>{success:boolean;message:string}; declareIndependence:(countryId:string)=>{success:boolean;message:string}; recruitUnit:(countryId:string,type:string,name:string,size:number)=>EngineResult; issueMilitaryOrder:(body:any)=>EngineResult; cancelMilitaryOrder:(orderId:string)=>EngineResult;
}
const GameContext=createContext<GameContextValue|null>(null);
const resourceNames:Record<ResourceKey,string>={food:"Food",steel:"Steel",oil:"Oil",aluminum:"Aluminum",copper:"Copper",rareMaterials:"Rare Materials",manpower:"Manpower",money:"Money",premium:"Premium"};
function adaptCountries(state:GameState):DemoCountry[]{ return state.countries.map(c=>({id:c.id,name:c.name,code:c.code,capital:c.capital,population:0,gdp:0,government:"strategic",status:"peace",treasury:0,militaryStrength:c.power,stability:80,color:c.color,bloc:c.bloc,region:"World",description:"Strategic power in the Global Dominion world."})); }
function adaptResources(state:GameState):DemoResource[]{ return (Object.keys(state.resources) as ResourceKey[]).map(k=>({type:k,name:resourceNames[k],amount:Math.round(state.resources[k].amount),production:state.resources[k].productionPerHour,consumption:state.resources[k].consumptionPerHour,unit:k==="money"?"GD$":"units"})); }
function adaptUnits(state:GameState):DemoUnit[]{ return state.units.map(u=>({id:u.id,type:u.type,name:u.name,size:u.strength,location:state.provinces.find(p=>p.id===u.provinceId)?.name??u.provinceId,morale:u.morale,supply:100,status:"ready",countryId:u.countryId,health:u.health,fuel:u.fuel,ammunition:u.ammunition})); }
function adaptWars(state:GameState):DemoWar[]{ return state.wars.map(w=>({id:w.id,name:w.name,attackerId:w.attackerId,defenderId:w.defenderId,status:w.status==="active"?"active":"ended",startedAt:w.startedAt,fronts:w.battleIds.map(id=>state.battles.find(b=>b.id===id)?.provinceId??"Front"),battles:w.battleIds.map(id=>{const b=state.battles.find(x=>x.id===id); return {id,name:b?.name??"Battle",location:state.provinces.find(p=>p.id===b?.provinceId)?.name??"Front",attackerStrength:b?.attackerStrength??0,defenderStrength:b?.defenderStrength??0,status:b?.status??"ongoing",day:1};})})); }
export function GameProvider({children}:{children:React.ReactNode}){
 const [state,setState]=useState<GameState>(()=>createGameState()); const [loaded,setLoaded]=useState(false); const [tickCount,setTickCount]=useState(0); const lastPersist=useRef(0);
 useEffect(()=>{ (async()=>{ const saved=await getItem<GameState>(GAME_KEY); if(saved){setState(reconcile(saved,Date.now()));} setLoaded(true); })(); },[]);
 const persist=useCallback(async(next:GameState)=>{ await setItem(GAME_KEY,next); lastPersist.current=Date.now(); },[]);
 const apply=useCallback((fn:(s:GameState)=>GameState|EngineResult)=>{ setState(prev=>{const raw=fn(reconcile(prev,Date.now())); const next="state" in raw?raw.state:raw; void persist(next); return next;}); setTickCount(x=>x+1); },[persist]);
 const refreshTimers=useCallback(()=>apply(s=>reconcile(s,Date.now())),[apply]);
 useEffect(()=>{ if(!loaded)return; const id=setInterval(refreshTimers,5000); const sub=AppState.addEventListener("change",next=>{if(next==="active")refreshTimers();}); return()=>{clearInterval(id);sub.remove();}; },[loaded,refreshTimers]);
 useEffect(()=>{ if(!loaded)return; if(Date.now()-lastPersist.current>15000) void persist(reconcile(state,Date.now())); },[state,loaded,persist]);
 const action=useCallback(<T extends any[]>(fn:(s:GameState,...args:T)=>EngineResult)=>(...args:T)=>{let out:EngineResult={ok:false,message:"",state}; setState(prev=>{out=fn(reconcile(prev,Date.now()),...args); if(out.ok) void persist(out.state); return out.ok?out.state:prev;}); setTickCount(x=>x+1); return out;},[persist,state]);
 const value=useMemo<GameContextValue>(()=>{
   const countries=adaptCountries(state), resources=adaptResources(state), units=adaptUnits(state), wars=adaptWars(state);
   const selectedCountryId=state.provinces.find(p=>p.id===state.selectedProvinceId)?.ownerId??state.player.countryId;
   return {state,countries,resources,units,wars,events:state.notifications,selectedCountryId,selectedProvinceId:state.selectedProvinceId,selectedCityId:state.selectedCityId,selectedArmyId:state.selectedArmyId,setSelectedCountryId:(id)=>{const p=state.provinces.find(x=>x.ownerId===id);setState(s=>({...s,selectedProvinceId:p?.id,selectedCityId:undefined}));},selectProvince:(id)=>setState(s=>({...s,selectedProvinceId:id,selectedCityId:undefined})),selectCity:(id)=>setState(s=>({...s,selectedCityId:id,selectedProvinceId:s.cities.find(c=>c.id===id)?.provinceId})),selectArmy:(id)=>setState(s=>({...s,selectedArmyId:id})),tickCount,advanceTick:refreshTimers,save:async()=>persist(reconcile(state,Date.now())),refreshTimers,
   startConstruction:action((s,p,t)=>startConstruction(s,p,t)),collectOutput:action((s,id)=>collectOutput(s,id)),upgradeBuilding:action((s,id)=>upgradeBuilding(s,id)),startResearch:action((s,id,p)=>startResearch(s,id,p??s.selectedProvinceId??"p_berlin")),startProduction:action((s,p,t,q)=>startProduction(s,p,t,q??1)),createArmy:action((s,p,n)=>createArmy(s,p,n)),assignUnits:action((s,a,u)=>assignUnits(s,a,u)),moveArmy:action((s,a,d)=>moveArmy(s,a,d)),attackProvince:action((s,a,d)=>attackProvince(s,a,d)),resolveBattle:action((s,id)=>resolveBattle(s,id)),marketTrade:action((s,r,q,side)=>marketTrade(s,r,q,side)),setDiplomacy:action((s,t,status)=>setDiplomacy(s,t,status)),inviteAllianceMember:action((s,id)=>inviteAllianceMember(s,id)),recruitAgent:action((s,p,m)=>recruitAgent(s,p,m)),sendChat:action((s,text,channel)=>sendChat(s,text,channel)),declareWar:action((s,t)=>declareWar(s,t)),changeRank:action((s,r)=>changeRank(s,r)),markNotificationRead:(id)=>setState(s=>markNotificationRead(s,id)),
   revolutions:[],startRevolution:()=>({success:false,message:"Revolutions are outside the current core campaign."}),supportIndependence:()=>({success:false,message:"Independence support is unavailable in this campaign."}),declareIndependence:()=>({success:false,message:"Independence is controlled by conquest and diplomacy."}),recruitUnit:(countryId,type,name,size)=>startProduction(reconcile(state,Date.now()),state.provinces.find(p=>p.ownerId===countryId)?.id??"p_berlin",type as UnitType,Math.max(1,Math.round(size/100))),issueMilitaryOrder:(body)=>body?.orderType==="attack"?attackProvince(reconcile(state,Date.now()),body.armyId,body.targetProvinceId):moveArmy(reconcile(state,Date.now()),body.armyId,body.destinationProvinceId),cancelMilitaryOrder:()=>({ok:false,message:"Orders cannot be cancelled after commitment in this build.",state})};
 },[state,tickCount,action,persist,refreshTimers]);
 return <GameContext.Provider value={value}>{children}</GameContext.Provider>;
}
export function useGame(){const v=useContext(GameContext);if(!v)throw new Error("useGame must be used within GameProvider");return v;}
