import React, { createContext, useCallback, useContext, useEffect, useState } from "react";
import { apiClient } from "../services/api";
import { DEMO_COUNTRIES, DEMO_MARKET, DEMO_RESOURCES, DEMO_UNITS, DEMO_WORLD_EVENTS, DEMO_WARS, DEMO_REVOLUTIONS, type DemoCountry, type DemoResource, type DemoUnit, type DemoWar, type DemoRevolution, type DemoBattle } from "../data/mock";

interface GameContextValue {
  countries: DemoCountry[]; resources: DemoResource[]; units: DemoUnit[]; events: typeof DEMO_WORLD_EVENTS; market: typeof DEMO_MARKET; wars: DemoWar[]; revolutions: DemoRevolution[];
  selectedCountryId: string | null; setSelectedCountryId: (id: string | null) => void; tickCount: number; advanceTick: () => void;
  startRevolution: (countryId:string, goal:"independence"|"regime_change"|"secession", leaderName:string)=>{success:boolean;message:string};
  supportIndependence:(countryId:string,amount?:number)=>{success:boolean;message:string};
  declareIndependence:(countryId:string)=>{success:boolean;message:string};
  declareWar:(attackerId:string,defenderId:string,warName:string)=>{success:boolean;message:string};
  resolveBattleStep:(warId:string,battleId:string)=>{success:boolean;message:string};
  recruitUnit:(countryId:string,type:string,name:string,size:number)=>{success:boolean;message:string};
  issueMilitaryOrder:(body:any)=>{success:boolean;message:string};
  cancelMilitaryOrder:(orderId:string)=>{success:boolean;message:string};
}
const GameContext=createContext<GameContextValue|null>(null);
const mapCountry=(c:any):DemoCountry=>({...c,description:c.description||`Strategic power of ${c.name}.`,canRevolt:c.canRevolt??false,independenceMovement:c.independenceMovement??0,bloc:c.bloc||"Independent",region:c.region||"Global",allies:c.allies||[],territories:c.territories||[],superpower:c.superpower??false});
const mapUnit=(u:any):DemoUnit=>({id:u.id,type:u.type,name:u.name,size:u.size??u.personnel??0,location:u.location||"Unknown",morale:u.morale??75,supply:u.supply??75,status:u.status||"ready",countryId:u.countryId,position:u.position,destination:u.destination,route:u.route||[],distanceKm:u.distanceKm,speedKmh:u.speedKmh,etaSeconds:u.etaSeconds,progress:u.progress,orderStatus:u.orderStatus,activeOrderId:u.activeOrderId,targetUnitId:u.targetUnitId,combatDomain:u.combatDomain,garrisonedCityId:u.garrisonedCityId,entrenchment:u.entrenchment,health:u.health,fuel:u.fuel,ammunition:u.ammunition});
const mapWar=(w:any):DemoWar=>({id:w.id,name:w.name||`${w.attackerCountryId} vs ${w.defenderCountryId}`,attackerId:w.attackerCountryId,defenderId:w.defenderCountryId,status:w.status||"active",startedAt:w.declaredAt||w.startedAt||new Date().toISOString(),fronts:w.fronts||[],battles:(w.battles||[]).map((b:any):DemoBattle=>({id:b.id,name:b.name||"Battle",location:b.location||b.territoryId||"Front",attackerStrength:b.attackerStrength??0,defenderStrength:b.defenderStrength??0,status:b.status||"ongoing",day:b.day??1}))});

export function GameProvider({children}:{children:React.ReactNode}){
 const [countries,setCountries]=useState<DemoCountry[]>(DEMO_COUNTRIES); const [resources,setResources]=useState<DemoResource[]>(DEMO_RESOURCES); const [units,setUnits]=useState<DemoUnit[]>(DEMO_UNITS); const [events,setEvents]=useState(DEMO_WORLD_EVENTS); const [market,setMarket]=useState(DEMO_MARKET); const [wars,setWars]=useState<DemoWar[]>(DEMO_WARS); const [revolutions,setRevolutions]=useState<DemoRevolution[]>(DEMO_REVOLUTIONS); const [selectedCountryId,setSelectedCountryId]=useState<string|null>("country_gnr"); const [tickCount,setTickCount]=useState(0);
 const refresh=useCallback(async()=>{try{const state:any=await apiClient.get("/strategy/state"); if(Array.isArray(state.countries))setCountries(state.countries.map(mapCountry)); if(Array.isArray(state.resources))setResources(state.resources); if(Array.isArray(state.units))setUnits(state.units.map(mapUnit)); if(Array.isArray(state.market))setMarket(state.market); if(Array.isArray(state.events))setEvents(state.events); if(Array.isArray(state.wars))setWars(state.wars.map(mapWar)); if(typeof state.tickCount==="number")setTickCount(state.tickCount);}catch{ /* keep functional local fallback */ }},[]);
 useEffect(()=>{refresh(); const id=setInterval(refresh,10000); return()=>clearInterval(id)},[refresh]);
 const advanceTick=useCallback(async()=>{try{await apiClient.post("/api/economy/tick",{});await refresh()}catch{setTickCount(t=>t+1)}},[refresh]);
 const pushEvent=(title:string,description:string,type:string)=>setEvents(prev=>[{id:`evt_${Date.now()}`,title,description,type,timestamp:new Date().toISOString()},...prev].slice(0,20) as any);
 const declareWar=useCallback((attackerId:string,defenderId:string,warName:string)=>{void (async()=>{try{const w:any=await apiClient.post("/wars/declare",{defenderCountryId:defenderId,reason:warName});setWars(prev=>[mapWar(w),...prev]);await refresh()}catch(e:any){pushEvent("War command failed",e?.message||"Server rejected the declaration.","military")}})(); return {success:true,message:`War order submitted against ${defenderId}.`}},[refresh]);
 const resolveBattleStep=useCallback((warId:string,battleId:string)=>{void (async()=>{try{await apiClient.post(`/wars/battles/${encodeURIComponent(battleId)}/resolve`,{warId});await refresh()}catch{}})();return {success:true,message:"Battle resolution order submitted to the server."}},[refresh]);
 const recruitUnit=useCallback((countryId:string,type:string,name:string,size:number)=>{void (async()=>{try{await apiClient.post("/military/recruit",{countryId,type,name,size});await refresh()}catch(e:any){pushEvent("Recruitment failed",e?.message||"Server rejected recruitment.","military")}})();return {success:true,message:`Recruitment order submitted for ${name}.`}},[refresh]);
 const issueMilitaryOrder=useCallback((body:any)=>{void (async()=>{try{await apiClient.post("/military/orders",body);await refresh()}catch(e:any){pushEvent("Military order rejected",e?.message||"Server rejected the order.","military")}})();return{success:true,message:`${String(body.orderType||"move").toUpperCase()} order submitted.`}},[refresh]);
 const cancelMilitaryOrder=useCallback((orderId:string)=>{void (async()=>{try{await apiClient.post(`/military/orders/${encodeURIComponent(orderId)}/cancel`,{});await refresh()}catch(e:any){pushEvent("Order cancellation failed",e?.message||"Server rejected the cancellation.","military")}})();return{success:true,message:"Cancellation submitted."}},[refresh]);
 const startRevolution=(countryId:string,goal:any,leaderName:string)=>{void (async()=>{try{await apiClient.post("/revolutions/start",{territoryId:countryId,goal,leaderName});await refresh()}catch(e:any){pushEvent("Revolution rejected",e?.message||"Server rejected the action.","politics")}})();return{success:true,message:"Revolution order submitted to the server."}};
 const supportIndependence=(countryId:string,amount=8)=>{void (async()=>{try{const r:any=await apiClient.post("/revolutions/support",{revolutionId:countryId,amount});setRevolutions(prev=>prev.map(x=>x.id===countryId?{...x,support:r.support}:x));await refresh()}catch(e:any){pushEvent("Support rejected",e?.message||"Server rejected the action.","politics")}})();return{success:true,message:"Support order submitted to the server."}};
 const declareIndependence=(countryId:string)=>{void (async()=>{try{await apiClient.post("/independence/declare",{countryId});await refresh()}catch(e:any){pushEvent("Independence rejected",e?.message||"Requirements not met.","politics")}})();return{success:true,message:"Independence declaration submitted to the server."}};
 return <GameContext.Provider value={{countries,resources,units,events,market,wars,revolutions,selectedCountryId,setSelectedCountryId,tickCount,advanceTick,startRevolution,supportIndependence,declareIndependence,declareWar,resolveBattleStep,recruitUnit,issueMilitaryOrder,cancelMilitaryOrder}}>{children}</GameContext.Provider>;
}
export function useGame(){const value=useContext(GameContext);if(!value)throw new Error("useGame must be used within GameProvider");return value;}
